name: Build Executable

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: putting gtest
      run: git clone https://github.com/google/googletest.git third-party/gtest

    - name: Configure CMake
      run: cmake -B build

    - name: Build Executable
      run: cmake --build build

    - name: Run Executable
      run: ./build/Facade

